<?php
return array (
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.kejilion.tk/m3u8/?url=',
    'sort' => '8',
    'tip' => '',
    'id' => 'qq',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇艺',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.kejilion.tk/m3u8/?url=',
    'sort' => '4',
    'tip' => '',
    'id' => 'qiyi',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.kejilion.tk/m3u8/?url=',
    'sort' => '3',
    'tip' => '',
    'id' => 'youku',
  ),
  'bilibili' => 
  array (
    'status' => '1',
    'from' => 'bilibili',
    'show' => 'B站',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.bozrc.com:4433/player/?url=',
    'sort' => '2',
    'tip' => '',
    'id' => 'bilibili',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.kejilion.tk/m3u8/?url=',
    'sort' => '2',
    'tip' => '',
    'id' => 'letv',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.kejilion.tk/m3u8/?url=',
    'sort' => '2',
    'tip' => '',
    'id' => 'mgtv',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.kejilion.tk/m3u8/?url=',
    'sort' => '2',
    'tip' => '',
    'id' => 'sohu',
  ),
  'xigua' => 
  array (
    'status' => '1',
    'from' => 'xigua',
    'show' => '西瓜',
    'des' => '',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.kejilion.tk/m3u8/?url=',
    'sort' => '2',
    'tip' => '',
    'id' => 'xigua',
  ),
  'gsm3u8' => 
  array (
    'status' => '1',
    'from' => 'gsm3u8',
    'show' => '光速',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'https://www.guangsujx.com/m3u8/?url=',
    'sort' => '1',
    'tip' => '',
    'id' => 'gsm3u8',
  ),
  'hnm3u8' => 
  array (
    'status' => '1',
    'from' => 'hnm3u8',
    'show' => '红牛',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'https://jx.kejilion.tk/m3u8/?url=',
    'sort' => '1',
    'tip' => '',
    'id' => 'hnm3u8',
  ),
  'kbm3u8' => 
  array (
    'status' => '1',
    'from' => 'kbm3u8',
    'show' => '快播',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1',
    'tip' => '',
    'id' => 'kbm3u8',
  ),
  'wjm3u8' => 
  array (
    'status' => '1',
    'from' => 'wjm3u8',
    'show' => '无尽',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'https://jx.kejilion.tk/m3u8/?url=',
    'sort' => '1',
    'tip' => '',
    'id' => 'wjm3u8',
  ),
  'm3u8' => 
  array (
    'status' => '1',
    'from' => 'm3u8',
    'show' => '云播',
    'des' => 'http://www.bbkdj.com/help/maccms.html',
    'target' => '_self',
    'ps' => '1',
    'parse' => '//jx.yparse.com/index.php?url=',
    'sort' => '0',
    'tip' => '无需播放器，在线播放',
    'id' => 'm3u8',
  ),
);